### ISSUE TITLE
Fragmenter value for APBtoTL

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#32]
Auto-generated code looks something like this:

  def getPMA1APBNodeTLAdapter(): TLInwardNode = {(
    PMA1APBNode
      := TLToAPB(false)
      := TLBuffer()
      := TLFragmenter(**(8/8)**, c.blackbox.cacheBlockBytes, holdFirstDeny=true)
  )}

The diplomacy complains about the 8/8 value, indicating that the minimum value in this case should be 4. When changed manually it works fine

**Comment by albertchen-sifive** [comment]
What version of `duh-scala` are you using? this should have been fixed in https://github.com/sifive/duh-scala/pull/23

**Comment by albertchen-sifive** [comment]
to clarify, the issue was that the `beatBytes` parameter of the `APBSlaveNode` was hard-coded to 4 when it should have been `dataWidth/8`. so the emitted code for the `TLFragmenter` actually is correct. It was an error in the `APBSlaveNode` that was not caught until this code fragment.

**Comment by v-krvavac** [comment]
Shouldn't it then be (32/8) instead of (8/8) which is generated currently? I did a fresh duh install and tried again today, the result is the same.

**Comment by albertchen-sifive** [comment]
What is the data width of your APB bus interface declared in the DUH document? If it is 8 then 8/8 is the correct value. 4 is not the correct value to put for this argument because it should be `dataWidth/8`. The error was not in the `TLFragmenter` parameters. it was in the `APBSlaveNode` instantiation. The `APBSlaveNode` was created with data width 4 instead of 8/8 which would explain why diplomacy complained that the minimum value was 4. Please check that the `beatBytes` parameter of `PMA1APBNode` is 8/8.

**Comment by v-krvavac** [comment]
Thanks for the explanation, works just fine now :)
